### PR TITLE
Callback for removed packets from OutstandingQueue

### PR DESCRIPTION
**Pull request by vaz985**
Implementation for a callback for the removal of packets from the OutstandingPackets queue. This enables the Observer to recover information about packets as they are leaving the OutstandingPackets queue. 

A helper function "removeOutstandingPackets" was created to handle the moving process if needed (at least one observer that uses this callback). The function resides in "quic/state/AckHandlers" because most of the removals are done there.

* I also changed some code to avoid checking if the callback exists after they emplaced.

### CODE REVIEW

**Comment by mjoras** [comment]
Can you clarify why exactly it's useful to observe the removal in addition to being declared lost/ACKed?

**Comment by vaz985** [comment]
I think every application that keeps track of packets in the wire could benefit from this. 

I'm building an application to guess which packets are likely to be lost due to self-induced congestion. This is done by modeling the behavior of a queue which needs the packet sent timestamp and if they were lost (to check the effectiveness of the model). The application keeps a minimum amount of information about the packet and holds it until it knows what happens to it. If i have access to the removed packets we can reduce the amount of information stored without the necessity of guessing which packets were removed by looking at the difference between the outstanding queue at each packetsWritten events (and i'm also bounded by those events to remove).

Ack’s can help but it would still need to check for packets that were lost after enough time to not remove before a possible spurious event. The remove callback facilitates this because mvfst already tracks for this case.

**Comment by mjoras** [comment]
Hmm I'm still a little bit confused. There's only two reasons a packet would get removed from the outstanding packet list: loss, or acknowledgment. In the latter case it gets removed immediately. In the former case the deletion is deferred for a while to facilitate spurious loss tracking, but that's it. The packet is, for all intents and purposes for mvfst, already removed.

Why can you not simply track it via loss/ack events? Why does it matter if you know when mvfst decides to actually

**Comment by vaz985** [comment]
> Why can you not simply track it via loss/ack events? Why does it matter if you know when mvfst decides to actually

I can track with loss/ack events and at the end it doesn't matter when mvfst decides, it is for convenience. Depending on the case, I may have to hold a lot of packets that were lost. Because we need to wait for a chance to be spurious, I'm left with packets that are not signaled in any way. With only the current callbacks and possibly a new ACK callback I still have to do something similar to [clearOldOutstandingPackets](https://github.com/facebookincubator/mvfst/blob/028f50d14fb3ae6d875cfc541bad33c5ca5ed1b9/quic/state/AckHandlers.cpp#L292) or keep looking at differences between outstanding lists.

**Comment by vaz985** [comment]
Changed the callback function to be responsible for sending the removed packets to every capable observer.

**Pull request closed without merging**
